[package]
name = "bld"
version = "0.1.0"
authors = ["Kostas Vlachos <kvl_93@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
yaml-rust = "0.4.4"
futures-util = "0.3.5"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }
shiplift = { git = "https://github.com/softprops/shiplift.git", branch = "master" } 
termcolor = "1.1.0"
actix-web = "3.0.2"
