[package]
name = "bld"
version = "0.1.0"
authors = ["Kostas Vlachos <kvl_93@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
yaml-rust = "0.4.4"
futures-util = "0.3.5"
shiplift = { git = "https://github.com/softprops/shiplift.git", branch = "master" } 
termcolor = "1.1.0"
actix-web = "3.1.0"
actix-web-actors = "3.0.0"
actix = "0.10.0"
awc = "2.0.0"
bytes = "0.5.6"
futures = "0.3.5"
actix-codec = "0.3.0"
env_logger = "0.8.1"
tokio = { version = "0.2.6", features = ["full"] }
serde_json = "1.0.59"
diesel = { version = "1.4.5", features = ["sqlite"] }
