[package]
name = "bld"
version = "0.1.0"
authors = ["Kostas Vlachos <kvl_93@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
yaml-rust = "0.4.4"
futures-util = "0.3.5"
shiplift = "0.7.0"
termcolor = "1.1.0"
actix-web = { version = "3.1.0", features = ["openssl"] }
actix-web-actors = "3.0.0"
actix = "0.10.0"
awc = "2.0.0"
bytes = "0.5.6"
futures = "0.3.5"
actix-codec = "0.3.0"
env_logger = "0.8.1"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.59"
diesel = { version = "1.4.5", features = ["sqlite"] }
uuid = { version = "0.8.1", features = ["v4"] }
actix-http = "2.1.0"
serde = "1.0.117"
oauth2 = { version = "3.0.0", features = ["futures-03"] }
serde_derive = "1.0.118"
actix-service = "1.0.6"
chrono = "0.4.19"
tar = "0.4.32"
async-raft = "0.6.0"
async-trait = "0.1.50"
anyhow = "1.0.40"
